import "./globals.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className="h-screen w-screen bg-neutral-50 overflow-auto">{children}</main>
      </body>
    </html>
  )
}
